// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVq9WzZNu8QZD6z3i0Ua9GAiyJBL-04J4',
    appId: '1:985682424544:web:a1e235b38726093818d685',
    messagingSenderId: '985682424544',
    projectId: 'pinjam-sahabat-27afd',
    authDomain: 'pinjam-sahabat-27afd.firebaseapp.com',
    storageBucket: 'pinjam-sahabat-27afd.appspot.com',
    measurementId: 'G-3R7NH57HXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9vlnyeYi5Mo14ePI6OgusKzI9rGPf8eo',
    appId: '1:985682424544:android:992f06c767b38a3118d685',
    messagingSenderId: '985682424544',
    projectId: 'pinjam-sahabat-27afd',
    storageBucket: 'pinjam-sahabat-27afd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyyxTyz5IZlgeFZfdM9Rwp0RZYIKVFzps',
    appId: '1:985682424544:ios:41ed7204214a052518d685',
    messagingSenderId: '985682424544',
    projectId: 'pinjam-sahabat-27afd',
    storageBucket: 'pinjam-sahabat-27afd.appspot.com',
    iosBundleId: 'com.example.sewaBarang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyyxTyz5IZlgeFZfdM9Rwp0RZYIKVFzps',
    appId: '1:985682424544:ios:3848da7680c1459518d685',
    messagingSenderId: '985682424544',
    projectId: 'pinjam-sahabat-27afd',
    storageBucket: 'pinjam-sahabat-27afd.appspot.com',
    iosBundleId: 'com.example.sewaBarang.RunnerTests',
  );
}
